### PR TITLE
Revamp 👀

### PR DESCRIPTION
**Pull request by jamcsu**
Yeet

### CODE REVIEW

**Comment by doddsy** [comment]
I'll peep this later today :eyes:

**Comment by jamcsu** [comment]
RE: @doddsy
Re-did the README, should be much more coherent now because I was actually thinking straight when I wrote it this time.

**Comment by doddsy** [comment]
Lovely, but a few problems:

- Performing `a!auth set` without a verification level returns `Successfully set this guild's authentication level to  | ().`
    - However running `a!auth get` afterwards shows the auth level is `0`.
    - Consider making it not change on incorrect command usage or making it say that the auth level was set to 0.
- Not sure if I was doing something wrong, but after setting Authentication Level to 5 and having an account join, `a!auth approve <user>` returned `<user> does not have an active authentication key.` This is the same message as `auth reveal`, so I'm not sure if something is overlapping?

**Comment by doddsy** [comment]
Once those are fixed I'm happy to merge. Not important but *maybe* just a quick cleanup of the README for readability would be nice. It's definitely follow-able but walls of text are always hard to read.

**Pull request closed without merging**
