### PR TITLE
Now this? This is epic. (AutoPunishments)

### PR DESCRIPTION
**Pull request by metronode-uk**
- This is a...
  - [ ] Superaction    
  - [x] Action
  - [ ] Snippet
- [x] I have followed the Guidelines for Contributing as closely as possible.
- [x] I have thoroughly tested my (super)action and ensured that it works properly, even when used incorrectly.
- [x] My action is not a wrapper/alias for another command - it has an actual use.

--------------------------------------------------------------------------------

### CODE REVIEW

**Comment by Cykreet** [comment]
horrendous, get the this shit out of here. closed.

**Comment by DracoClaw** [comment]
Couldn't the role you use to test if the user is in the server be set as the Muted role and save on some logic?

**Review by JaM3141 — CHANGES_REQUESTED** [review]
- Your file name(s) do(es)n't follow the [Folder Format Requirements](https://github.com/atlasbot/community-actions#folder-format-requirements)
- The default punishments are ***extremely vicious***, to put it simply. My personal preference is that actions should be as plug-and-play as possible. Those defaults seem to force the user to edit a *lot* of stuff before they even start using the action.

Other than that, no issues as far as I can tell.

**Review by Cykreet — APPROVED** [review]

**Comment by JaM3141** [comment]
Inactive, closing. Resubmit PR on [new repo](https://github.com/sylo-digital/atlas-community-actions).

**Pull request closed without merging**
